import type { Metadata } from "next";

import dayjs from "dayjs";
import vi from "dayjs/locale/vi";
import relativeTime from "dayjs/plugin/relativeTime";

import { CMainLayout } from "@/common/components/layouts";

import { montserrat, raleway, roboto, sourceSerif4 } from "../fonts";

dayjs.extend(relativeTime);
dayjs.locale(vi);

import "react-loading-skeleton/dist/skeleton.css";
import "swiper/css";
import "../../styles/index.scss";
import "./globals.css";

//#region Metadata
export const metadata: Metadata = {
    title: "Cái web của tui",
    description: "Generated by create next app",
};
//#endregion

interface IRootLayoutProps {
    children: React.ReactNode;
    params: { lang: string };
}

export default function RootLayout({ children }: IRootLayoutProps) {
    return (
        <html
            className={`${sourceSerif4.variable} ${roboto.variable} ${raleway.variable} ${montserrat.variable}`}
        >
            <head>
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
                    rel="stylesheet"
                ></link>
            </head>
            <body>
                <CMainLayout>{children}</CMainLayout>
            </body>
        </html>
    );
}

// <title>{{ $title }}</title>
// <meta name="description" content="{{ $description }}">
// <meta property="og:title" content="{{ $title }}"/>
// <meta property="og:type" content="{{ $type }}"/>
// <meta property="og:url" content="{{ url()->current() }}"/>
// <meta property="og:image" content="{{ $image }}"/>
// <meta property="og:image:alt" content="{{ $imageAlt }}"/>
// <meta property="og:description" content="{{ $description }}"/>
