import { CMainLayout } from "@/common/components/layouts";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import vi from "dayjs/locale/vi";

import { montserrat, raleway, roboto, sourceSerif4 } from "./fonts";

dayjs.extend(relativeTime);
dayjs.locale(vi);

import "swiper/css";
import "./globals.css";

export const metadata = {
    title: "Cái web của tui",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            className={`${sourceSerif4.variable} ${roboto.variable} ${raleway.variable} ${montserrat.variable}`}
        >
            <head>
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
                    rel="stylesheet"
                ></link>
            </head>
            <body>
                <CMainLayout>{children}</CMainLayout>
            </body>
        </html>
    );
}
