import { CMainLayout } from "@/common/components/layouts";
import { Source_Serif_4 } from "next/font/google";

import "./globals.css";

const sourceSerif4 = Source_Serif_4({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-source-serif-4",
});

export const metadata = {
    title: "Cái web của tui",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={sourceSerif4.variable}>
            <head>
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
                    rel="stylesheet"
                ></link>
            </head>
            <body>
                <CMainLayout>{children}</CMainLayout>
            </body>
        </html>
    );
}
