import "./globals.css";

import { Source_Serif_4 } from "next/font/google";

const serif4 = Source_Serif_4({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-source-serif-4",
});

export const metadata = {
    title: "Cái web của tui",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={serif4.variable}>
            <body>{children}</body>
        </html>
    );
}
